name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  composer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2', '8.3']
    name: Composer PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - run: composer update --no-progress --no-interaction
      - run: composer outdated -D --strict --ignore=phpunit/phpunit --ignore=illuminate/support

  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2', '8.3']
    name: PHPUnit PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
      - run: composer update --no-progress --no-interaction
      - run: vendor/bin/phpunit --coverage-clover=coverage.xml
        env:
          XDEBUG_MODE: coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2', '8.3']
    name: PHPStan PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - run: composer update --no-progress --no-interaction
      - run: vendor/bin/phpstan analyze src --level=5 --no-progress

  phpstan_lowest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2', '8.3']
    name: PHPStan Lowest PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - run: composer update --prefer-lowest --no-progress --no-interaction
      - run: vendor/bin/phpstan analyze src --level=5 --no-progress

  codesniffer:
    runs-on: ubuntu-latest
    name: PHPCS
    steps:
      - uses: actions/checkout@v2
      - run: composer update --no-progress --no-interaction
      - run: vendor/bin/phpcs src --standard=PSR2 -n
